# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param Cov the number of samples
#' @param p the number of between-sample random numbers
#' @param q 111
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
naive_estimator <- function(Cov, p, q) {
    .Call('_SA24204172_naive_estimator', PACKAGE = 'SA24204172', Cov, p, q)
}

