# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A estimator using Rcpp
#' @description A estimator using Rcpp
#' @param Cov covariance matrix
#' @param p dim1
#' @param q dim2
#' @return solution
#' @examples
#' \dontrun{
#' result <- naive_estimator(Cov,p,q)
#' }
#' @export
naive_estimator <- function(Cov, p, q) {
    .Call('_SA24204172_naive_estimator', PACKAGE = 'SA24204172', Cov, p, q)
}

